# Generated by Django 5.0.7 on 2024-07-21 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/product/')),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.AlterModelOptions(
            name='farmer',
            options={'verbose_name': 'Farmer'},
        ),
        migrations.AddField(
            model_name='farmer',
            name='mobile',
            field=models.CharField(default='12345678', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='total_area',
            field=models.IntegerField(default='123455'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.IntegerField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('description', models.TextField(max_length=300)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.farmer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.product')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/treatment/')),
                ('description', models.TextField(max_length=300)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.crop')),
            ],
        ),
    ]
