# Generated by Django 5.0.7 on 2024-07-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tracker', '0002_product_alter_farmer_options_farmer_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='farmer_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='farmer_user_permissions', to='auth.permission'),
        ),
    ]
